# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8771a8fe54bc7a6712616cf80e3c2f2c44040b6d3cc8267333e7a3f0a575fa78d5a79704777d7d510bdb6390f4695d88be4c729ffd21abaa44470fb921afd480

test:
  secret_key_base: 07694eab9947f547174551b91367bc2f33d362f91cb9d7108be01ec411063713cd45d7018dbdf4d2208d36c9d0e91cc35f539900b270fda6a18dd900d76eab29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
